// <auto-generated />
using System;
using BrainstormingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrainstormingApp.Data.Migrations
{
    [DbContext(typeof(BrainstormingAppContext))]
    [Migration("20190924101907_Added new default value in data context class for message property messagearchived.")]
    partial class Addednewdefaultvalueindatacontextclassformessagepropertymessagearchived
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrainstormingApp.Domain.BrainstormingRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("BrainstormingApp.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BrainstormingRoomId");

                    b.Property<DateTime?>("MessageArchived");

                    b.Property<DateTime>("MessageCreated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("MessageText");

                    b.Property<string>("UserNick");

                    b.HasKey("Id");

                    b.HasIndex("BrainstormingRoomId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BrainstormingApp.Domain.Message", b =>
                {
                    b.HasOne("BrainstormingApp.Domain.BrainstormingRoom")
                        .WithMany("Messages")
                        .HasForeignKey("BrainstormingRoomId");
                });
#pragma warning restore 612, 618
        }
    }
}
